#ifndef STATUS_BAR
#define STATUS_BAR

#define STATUS_BAR_ROW 0
#if TERMINAL_COLS >= 100
#define STATUS_USED_LABEL (TERMINAL_COLS - 60)
#define STATUS_USED_VALUE (TERMINAL_COLS - 54)
#define STATUS_FREE_LABEL (TERMINAL_COLS - 45)
#define STATUS_FREE_VALUE (TERMINAL_COLS - 39)
#define STATUS_PIDS_LABEL (TERMINAL_COLS - 28)
#define STATUS_PIDS_VALUE (TERMINAL_COLS - 22)
#define STATUS_UPTIME_LABEL (TERMINAL_COLS - 15)
#define STATUS_UPTIME_VALUE (TERMINAL_COLS - 7)
#else
#define STATUS_USED_LABEL 8 
#define STATUS_USED_VALUE 13
#define STATUS_FREE_LABEL 22
#define STATUS_FREE_VALUE 27
#define STATUS_PIDS_LABEL 36
#define STATUS_PIDS_VALUE 41
#define STATUS_UPTIME_LABEL 43
#define STATUS_UPTIME_VALUE 51
#endif

void update_status_bar();

#endif
