#ifndef PCH_H
#define PCH_H

#include "../shared/abi-types.h"
#include "../shared/string.h"
#include "../shared/math.h"
#include "../shared/mem.h"
#include "../shared/types.h"
#include "cpu/idt.h"
#include "cpu/exceptions.h"
#include "cpu/syscall.h"
#include "cpu/gdt.h"
#include "drivers/ata-disk.h"
#include "drivers/keyboard.h"
#include "drivers/mouse.h"
#include "drivers/timer.h"
#include "drivers/vga-graphics.h"
#include "drivers/terminal.h"
#include "kernel/kernel.h"
#include "kernel/config.h"
#include "kernel/frame.h"
#include "kernel/kmalloc.h"
#include "kernel/page-table.h"
#include "kernel/process-control-block.h"
#include "kernel/scheduler.h"
#include "kernel/stdin.h"
#include "kernel/event.h"
#include "kernel/window.h"
#include "lib/fat16.h"
#include "lib/status-bar.h"
#include "lib/font.h"
#include "lib/desktop.h"

#endif
